name = input("what is your name? ")
print("Hellow " + name)
birth_year = input("Enter your birth year: ")
age = 2025 - int(birth_year)
print("you are " + str(age) + " years old")
first = input("First: ")
second = input("Second: ")
sum = float(first) + float(second)
print("Sum: " + str(sum))
course = "python for beginners"
print(course.upper())
print(course)
print(course.lower())
print(course.find('y'))
print(course.replace("for","4")) 